### ISSUE TITLE
Won't work in Windows 8.1

### ISSUE THREAD

**Issue by GalaxyMaster2** [patriksletmo/Dota2Translator#13] opened 2014-12-02 20:37 UTC
I downloaded the latest version, installed it and got the message that winpcap was not compatible with windows 8. I saw that other people had the same problem and it got fixed by downloading a later version of winpcap from the official website. So I did that, installed it and then reinstalled dota2translator. Everything went fine and I restarted for good measure. I started up dota 2, then started up the translator. I pressed the add overlay button, it switched back to dota 2, but then nothing happened afterwards. I think it is supposed to leave a message if it successfully added the overlay, but I got nothing. If you could help me fix this problem it would be very nice.

**Comment by GalaxyMaster2** [comment] 2014-12-04 10:04
I got it working, but not completely. The translator works, I've tested it in a lobby. But it still does not load the overlay. I need to alt-tab out of the game to read the translations. This isn't a very big deal, but still annoying. If you need any extra information to fix the problem, ask me.

**Comment by turtlefish** [comment] 2014-12-04 17:29
How did you get the translator working?

**Comment by GalaxyMaster2** [comment] 2014-12-04 20:33
I don't remember exactly, but I'll try. First of all make sure you installed winpcap 4.1.3 before installing the translator. After that restart your pc. Then open dota 2, set it to borderless windowed mode and then quit it. Open the translator, then open dota 2. Make a lobby for yourself (don't use local lobby, but use a regular one) and pick a hero and get in game. Then alt tab out and click add overlay. You will get back to dota 2. Then just type something in chat like "hola", or "bonjour" or something similar. For me it worked at this point, just alt tab out to see the translation.

**Comment by patriksletmo** [comment] 2014-12-06 21:20
@GalaxyMaster2 Don't you see the message "Overlay added!"? If not, please post your log here. It's located in %APPDATA%/Dota 2 Translator/log.txt (C:/Users/MyUser/AppData/Roaming/Dota 2 Translator/log.txt)

**Comment by GalaxyMaster2** [comment] 2014-12-06 21:31
Ah, the log. I checked that immediately when I noticed it wasn't working as intended. Everything seemed fine in there, but I'll put it in here anyways.

[Program started at 04/12/2014 15:02]
Hooking DirectX functions...
Hooking EndScene at 1778625584
Hooking Reset at 1778628592
All DirectX functions hooked!

I don't see how this would be useful, as there doesn't seem to be a problem, but here you go anyways. Thanks in advance!

**Comment by patriksletmo** [comment] 2014-12-06 22:27
Strange, that indicates that both the overlay rendering and inter-process communication between the program and overlay is working. You don't happen to run some other overlay or recording/broadcasting software which might interfere?

**Comment by GalaxyMaster2** [comment] 2014-12-06 22:29
Well, I do use Razer Gamebooster because I really like the online savegame backup and the fps meter is also handy for games that don't have a in-built one. I could try not using it, but I don't have time for that now. Otherwise I don't think there is anything else that could have to do with this.

**Comment by patriksletmo** [comment] 2014-12-06 22:35
Seems like the fps meter is the issue then. It hooks the same function as the translator, and depending on the implementation this could result in one of the overlays (or the entire program, but that doesn't seem to be the case here) not functioning correctly.

I'm closing this issue as the cause has been nailed down. Feel free to open it again if you like.

**Comment by GalaxyMaster2** [comment] 2014-12-07 13:28
I tried it with the gamebooster closed, so that the fps meter was disabled for sure, and it still didn't work. The translator itself works great, but the overlay still doesn't appear.

**Comment by GalaxyMaster2** [comment] 2014-12-07 13:29
Also, I cannot reopen this for some reason.

**Comment by patriksletmo** [comment] 2014-12-12 09:32
Could you use [Process Explorer](http://technet.microsoft.com/en-us/sysinternals/bb896653.aspx) to retrieve a list of all loaded dlls in dota.exe (explained [here](http://kb.froglogic.com/display/KB/Getting+a+list+of+DLLs+currently+loaded+in+a+process))? This would help in determining what software interferes with the overlay.

**Comment by GalaxyMaster2** [comment] 2014-12-12 22:35
I have made 2 lists, 1 without the translator running and 1 when I tried to add the overlay. Hope this is ok.

Without translator:
http://pastebin.com/DtSWXz8d

With translator:
http://pastebin.com/AtY6N4Ny

EDIT: Looks like I've already found the problem. On line 141 of the first dll list I've found this: "EasyHook32.dll  EasyHook Native DLL (32-bit) (beta) - r73841    easyhook.codeplex.com   C:\Program Files (x86)\Razer\Razer Cortex\EasyHook32.dll"
It looks like it is the razer game booster thingy. I don't know why it is hooking into dota 2 because it has nothing to overlay. I've disabled the fps meter and the translator wouldn't work when I shut down the game booster. Is there any way to prevent it from hooking into dota 2? It doesn't seem to be doing anything.

**Comment by patriksletmo** [comment] 2014-12-15 18:09
After testing the translator with some Razer software installed and running I've managed to track down the problem to being a conflict with Razer Synapse (not Cortex). Shutting down Razer Synapse but having Razer Cortex still running (with booster and fps overlay) works for me. When Razer Synapse is running the overlay won't render.

Can you see if you can duplicate the described behavior?

**Comment by GalaxyMaster2** [comment] 2014-12-15 20:35
Well, I could try tomorrow. But I don't know if this could work for me as I require synapse to be running for my equaliser to work. Otherwise my sound setup would be completely screwed. Either way, I'll try it tomorrow and post here.

**Comment by iflyairplanes** [comment] 2014-12-16 15:26
@patriksletmo After testing the translator with and without Razer Synapse V1.18.18.23036 I can confirm that your findings are accurate. After some quick testing it seems that it's the fault of RazerHook32.dll 

Could possibly unloading the dll and loading it again after the translator has been loaded be a work-around?

**Comment by GalaxyMaster2** [comment] 2014-12-16 16:53
@fernmndez Hmm, I see that it is part of their so called "in game engine". It looks like the only thing it does is add an overlay and the only software I know of that has an in game overlay is their razer comms software. It has an overlay similar to the steam overlay. I don't know if the "in game engine" is part of comms, because I don't have that running while playing dota 2.

EDIT: It looks like it is part of comms, I found some files including ui images that match the ui of razer comms.

**Comment by GalaxyMaster2** [comment] 2014-12-17 16:44
I solved it! I took a look in the razer gamebooster to see if you could stop processes when you launch a game, and I selected the razeringameengine.exe. Decided to give it a try and IT WORKS! Thanks for all of your help and your amazing program!

**Closed as completed** 2014-12-17 19:17 UTC
